name: "Stale"
description: "Manages stale issues and pull requests."
author: "tjrgg"
inputs:
    repo-token:
        description: "Repository token (can be passed in using {{ secrets.GITHUB_TOKEN }})"
        required: true
    days-before-close:
        description: "The number of days of inactivity an issue should have before closing"
        default: "90"
        required: false
    days-before-stale:
        description: "The number of days of inactivity an issue should have before marking it stale"
        default: "30"
        required: false
    stale-label:
        description: "The label to apply to stale issues"
        default: "stale"
        required: false
runs:
    using: "node12"
    main: "dist/index.js"
